# A new way to visualize models

```{r message=FALSE, echo=FALSE}
library(knitr)
knitr::opts_chunk$set(tidy = FALSE, message=FALSE, warning=FALSE, fig.align='center')
```

```{r echo=TRUE}
library(predcomps)
library(ggplot2)
```

## Input Generation


```{r CreateInputFeatures}
N <- 100
v1 <- rnorm(N)
v2 <- rnorm(N)
df <- data.frame(v1, v2)

pairs <- GetPairs(df, "v1", "v2")
str(pairs)

predictionFunction <- function(v1,v2) v1*v2
pairs$yOld <- predictionFunction(pairs$v1,pairs$v2)
pairs$yNew <- predictionFunction(pairs$v1.B,pairs$v2)

library(plyr)
pairsToPlot <- ddply(subset(pairs, v1.B > v1), "OriginalRowNumber", function(df) {
  df[sample.int(nrow(df), size=1, prob=df$Weight), ]
  })

ggplot(pairsToPlot) +
  geom_segment(aes(x = v1, y = yOld, xend = v1.B, yend = yNew), 
               arrow = arrow(length = unit(0.5, "cm")))


predictionFunction <- function(v1,v2) v1 + v2 
pairs$yOld <- predictionFunction(pairs$v1,pairs$v2)
pairs$yNew <- predictionFunction(pairs$v1.B,pairs$v2)

pairsToPlot <- ddply(subset(pairs, v1.B > v1), "OriginalRowNumber", function(df) {
  df[sample.int(nrow(df), size=1, prob=df$Weight), ]
  })

ggplot(pairsToPlot) +
  geom_segment(aes(x = v1, y = yOld, xend = v1.B, yend = yNew), 
               arrow = arrow(length = unit(0.5, "cm")))

```
